# @package _global_

defaults:
  - override /data: mv_recon

name: mv_recon

eval_models:
  - pi3
  - pi3_exrot
  - vggt_pointhead        # point head instead of unprojected depth for mv_recon
  - vggt_exrot_pointhead  # point head instead of unprojected depth for mv_recon
  - worldmirror
  - worldmirror_exrot

eval_datasets:
  - 7scenes-sparse
  - 7scenes-dense
  - NRGBD-sparse
  - NRGBD-dense
  - DTU
  - ETH3D
  - UnSceneRecon

no_crop: True
load_img_size: 518

device: cuda

verbose: False

seed: 42

save_suffix: null
