# @package _global_

defaults:
  - override /data: relpose-angular

name: relpose-angular

eval_models:
  - pi3
  - pi3_exrot
  - vggt
  - vggt_exrot
  - worldmirror
  - worldmirror_exrot

eval_datasets:
  - Re10K
  # - CO3Dv2
  - ETH3D

no_crop: False
load_img_size: 512

device: cuda

verbose: False

seed: 42

save_suffix: null
